package main

import (
  "fmt"
  "strings"
  "net/http"
  "io/ioutil"
)

func main() {

  url := "https://auth.atlassian.com/oauth/token"
  method := "POST"

  payload := strings.NewReader("{\"grant_type\": \"authorization_code\",\"client_id\": \"JIRA_CLIENT_ID\",\"client_secret\": \"JIRA_CLIENT_SECRET\",\"code\": \"JIRA_AUTH_CALLBACK_CODE\",\"redirect_uri\": \"http://localhost:3001/jira/oauth/callback\"}")

  client := &http.Client {
  }
  req, err := http.NewRequest(method, url, payload)

  if err != nil {
    fmt.Println(err)
  }
  req.Header.Add("Content-Type", "application/json")
  // req.Header.Add("Cookie", "did=s%3Av0%3A779a86e0-76eb-11eb-aaac-5f24fe80c3fc.6Bc%2BmQRds8h1etVqJoFUx%2FK7bAKkc076Y%2BmObZ%2By3yg; did_compat=s%3Av0%3A779a86e0-76eb-11eb-aaac-5f24fe80c3fc.6Bc%2BmQRds8h1etVqJoFUx%2FK7bAKkc076Y%2BmObZ%2By3yg")
  //  generated by curl in postman?
  res, err := client.Do(req)
  defer res.Body.Close()
  body, err := ioutil.ReadAll(res.Body)

  fmt.Println(string(body))
}
